buildDebSbuild defaultTargets: 'bullseye-armhf bullseye-arm64',
               defaultWbdevImage: 'contactless/devenv:latest_bullseye',
               defaultRunLintian: true,
               defaultStyleCheckDirs: 'src test',
               defaultScaWbdevTarget: 'bullseye-armhf',
               defaultClangTidyPreHook: 'make open62541_build',
               defaultRunCoverage: true,
               defaultCoverageMin: '30',
               defaultDoCoverallsReporting: true,
               defaultBuildNode: 'heavy-duty'
